version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/git-action
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu/git-action
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStop:
    - location: scripts/kill.sh
      timeout: 3600
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 3600
