version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/git-action

permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root

hooks:
  ApplicationStop:
    - location: scripts/kill.sh
      timeout: 3600
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 3600
