spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: back123



jwt:
  secretkey: ${TOKEN_SECRET}
  accessTokenExpiration: 1000*60*60*12
  refreshTokenExpiration: 1000*60*60*24*14
