server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flint_local?serverTimezone=Asia/Seoul
    username: admin
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secretKey: ${TOKEN_SECRET}
  accessTokenExpiration: 43200000 #12시간
  refreshTokenExpiration: 1209600000  #2주

email:
  id: jsw5913@gmail.com
  password: ${EMAIL_PASSWORD}
  expiration: 300000


cloud:
  aws:
    s3:
      bucket: test
    credentials:
      access-key: test
      secret-key: test
    region:
      static: test
      auto: false
    stack:
      auto: false

logging:
  slack:
    webhook-uri: http://localhost:8080/log-callback
  config: classpath:logback-spring.xml

