spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: back123



jwt:
  secretKey: ${TOKEN_SECRET}
  accessTokenExpiration: 43200000 #12시간
  refreshTokenExpiration: 1209600000  #2주

email:
  id: jsw5913@gmail.com
  password: ${EMAIL_PASSWORD}



