



jwt:
  secretKey: ${TOKEN_SECRET}
  accessTokenExpiration: 43200000 #12시간
  refreshTokenExpiration: 1209600000  #2주

email:
  id: jsw5913@gmail.com
  password: ${EMAIL_PASSWORD}
  expiration: 300000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flint_local?serverTimezone=Asia/Seoul
    username: admin
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show-sql: true

  data:
    redis:
      host: localhost
      port: 6379






